version: '3.9'
services:
  my-wasemeshi-ap:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./my-wasemeshi:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "cd /usr/src/app && yarn && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true